spring:
  application:
    name: tic-tac-toe
  datasource:
    url: jdbc:mariadb://localhost:5000/testdb?createDatabaseIfNotExist=true
    username: someuser
    password: somepass
    driverClassName: org.mariadb.jdbc.Driver