spring.datasource.url: jdbc:mysql://localhost:3306/game?createDatabaseIfNotExist=true
spring.datasource.username: root
spring.datasource.password: 380500850614Lucky
spring.datasource.driver-class-name: com.mysql.jdbc.Driver